### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by DevAlien** [DevAlien/workspaces#32]
Tasks/changelog for release 3.1.0

Fixes
- [x] Fix run in terminal #23 
- [x] Fix Open quick launcher via the knob menu #21 
- [x] Fix crash when clicking on link on about dialog #21
- [x] Close quick launcher when selecting an item, unless you press CTRL #14 
- [x] Fixes visual issues on Switches, they were squashed

Improvements

- [x] Make the workspaces in the left list sortables with drag and drop
- [x] Make the items in the left list sortables with drag and drop
- [x] Items can be moved in another workspace just with drag and drop
- [x] Workspaces are editable
- [x] Workspaces are deletable (should display a warning message)
- [x] Workspaces will display an image in the list, if they have one
- [x] Items now have a blue dot indicating that they are part of the auto-run. (maybe we should add an icon if the item will run in the terminal?)
